server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: tb-provider-two
  datasource:
    driver-class-name: ${datasource.driver-class-name}
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

mybatis:
  configuration:
    map-underscore-to-camel-case: true  #═Нит├Ч├ч
  #mapper-locations:
